# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  BIN: ./bin
  SRC: '*.go'
  CLI: cnv

tasks:
  install:
    deps:
      - cli
    cmds:
      - sudo install {{.BIN}}/{{.CLI}} /usr/local/bin/
  fmt:
    cmds:
      - gofmt -l {{.SRC}} || (gofmt -d $(SRC); exit 1)

  lint:
    cmds:
      - golangci-lint run -v

  test: 
    deps: 
      - install_deps 
      - lint
    cmds:
      - richgo test -v ./...

  td2y: 
    deps: 
      - install_deps 
      - lint
    cmds:
      - bin/cnv d2y -i example/H4461790550_1.TER
                
  cli: 
    cmds:
      - mkdir -p {{.BIN}}
      - go build -o {{.BIN}}/{{.CLI}}

  wcli: 
    cmds:
      - mkdir -p {{.BIN}}
      - env GOOS=windows GOARCH=amd64 go build -o {{.BIN}}/{{.CLI}}.exe

  install_deps:
    cmds:
      - go get -v ./...

  clean:
    cmds:
      - rm -rf {{.BIN}}
  default:
    deps:
      - cli
    cmds:
      # - task -l
      - echo "{{.GREETING}}"

    silent: true
